feat: Add a more realistic example
This hangs because if I uncomment line 91 we get a compile error:

 wink@3900x 23-02-21T22:05:08.677Z:~/prgs/rust/myrepos/exper_dynamic_crossbeam_channel_select (main|REBASE 2/3)
 $ cargo build
    Compiling exper_dynamic_crossbeam_channel_select v0.1.0 (/home/wink/prgs/rust/myrepos/exper_dynamic_crossbeam_channel_select)
 error[E0502]: cannot borrow `worker_our_receivers` as mutable because it is also borrowed as immutable
   --> src/main.rs:90:29
    |
 90 | ...                   worker_our_receivers.push(our_rx);
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
 91 | ...                   sel.recv(worker_our_receivers.last().unwrap());
    |                       ----------------------------------------------
    |                       |        |
    |                       |        immutable borrow occurs here
    |                       immutable borrow later used here

 For more information about this error, try `rustc --explain E0502`.
 error: could not compile `exper_dynamic_crossbeam_channel_select` due to previous error